using System;

namespace Code.StatusEffectSystem
{
    public enum StatusEffectEnum
    {
        NONE = 0, DEF_STATUS = 1, HP_STATUS = 2, SPEED_STATUS = 4, HEALTH_REGEN = 8, DAMAGE_MODIFY_STATUS = 16, DAMAGE_DEMODIFY_STATUS = 32, RELOAD_SPEED_STATUS = 64, ADDITIONAL_DAMAGE = 128, DAMAGE_STORING = 256, DOT = 512, SHIELD = 1024, DMGINCREASE = 2048, FIRERATE_STATUS = 4096, BULLET_REDUCE_STATUS = 8192
    }
}
